from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BookEntry:
    canonical: str
    english_aliases: tuple[str, ...] = ()
    english_abbreviations: tuple[str, ...] = ()
    telugu_aliases: tuple[str, ...] = ()
    long_church_names: tuple[str, ...] = ()
    spoken_variants: tuple[str, ...] = ()

    @property
    def aliases(self) -> tuple[str, ...]:
        seen: set[str] = set()
        result: list[str] = []
        for t in (
            self.english_aliases + self.english_abbreviations
            + self.telugu_aliases + self.long_church_names
            + self.spoken_variants
        ):
            if t not in seen:
                seen.add(t)
                result.append(t)
        return tuple(result)


BOOKS: tuple[BookEntry, ...] = (
    # ---- Pentateuch ----
    BookEntry("Genesis",
        english_aliases=("genesis",),
        english_abbreviations=("gen", "ge"),
        telugu_aliases=("ఆదికాండము", "ఆదికాండం"),
        long_church_names=("ఆదికాండము గ్రంథము",),
        spoken_variants=("ఆది",),
    ),
    BookEntry("Exodus",
        english_aliases=("exodus",),
        english_abbreviations=("ex", "exo"),
        telugu_aliases=("నిర్గమకాండము", "నిర్గమకాండం"),
        long_church_names=("నిర్గమకాండము గ్రంథము",),
        spoken_variants=("నిర్గమ",),
    ),
    BookEntry("Leviticus",
        english_aliases=("leviticus",),
        english_abbreviations=("lev", "lv"),
        telugu_aliases=("లేవీయకాండము", "లేవీయకాండం"),
        long_church_names=("లేవీయకాండము గ్రంథము",),
        spoken_variants=("లేవీయ",),
    ),
    BookEntry("Numbers",
        english_aliases=("numbers",),
        english_abbreviations=("num", "nm"),
        telugu_aliases=("సంఖ్యాకాండము", "సంఖ్యాకాండం"),
        long_church_names=("సంఖ్యాకాండము గ్రంథము",),
        spoken_variants=("సంఖ్యా",),
    ),
    BookEntry("Deuteronomy",
        english_aliases=("deuteronomy",),
        english_abbreviations=("deut", "dt"),
        telugu_aliases=("ద్వితీయోపదేశకాండము", "ద్వితీయోపదేశకాండం"),
        long_church_names=("ద్వితీయోపదేశకాండము గ్రంథము",),
        spoken_variants=("ద్వితీయో", "ద్వితీయ"),
    ),

    # ---- Historical books ----
    BookEntry("Joshua",
        english_aliases=("joshua",),
        english_abbreviations=("josh", "jos"),
        telugu_aliases=("యెహోషువ",),
        long_church_names=("యెహోషువ గ్రంథము", "యెహోషువ గ్రంథం"),
        spoken_variants=("యెహో",),
    ),
    BookEntry("Judges",
        english_aliases=("judges",),
        english_abbreviations=("judg", "jdg"),
        telugu_aliases=("న్యాయాధిపతులు",),
        long_church_names=("న్యాయాధిపతుల గ్రంథము", "న్యాయాధిపతుల గ్రంథం"),
        spoken_variants=("న్యాయా", "న్యాయాధిపతులు"),
    ),
    BookEntry("Ruth",
        english_aliases=("ruth",),
        english_abbreviations=("rut", "ru"),
        telugu_aliases=("రూతు",),
        long_church_names=("రూతు గ్రంథము", "రూతు గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("1 Samuel",
        english_aliases=("1 samuel", "first samuel"),
        english_abbreviations=("1 sam", "1sm"),
        telugu_aliases=("1 సమూయేలు",),
        long_church_names=("మొదటి సమూయేలు గ్రంథము",),
        spoken_variants=("మొదటి సమూయేలు",),
    ),
    BookEntry("2 Samuel",
        english_aliases=("2 samuel", "second samuel"),
        english_abbreviations=("2 sam", "2sm"),
        telugu_aliases=("2 సమూయేలు",),
        long_church_names=("రెండవ సమూయేలు గ్రంథము",),
        spoken_variants=("రెండవ సమూయేలు",),
    ),
    BookEntry("1 Kings",
        english_aliases=("1 kings", "first kings"),
        english_abbreviations=("1 kgs", "1ki"),
        telugu_aliases=("1 రాజులు",),
        long_church_names=("మొదటి రాజుల గ్రంథము",),
        spoken_variants=("మొదటి రాజులు",),
    ),
    BookEntry("2 Kings",
        english_aliases=("2 kings", "second kings"),
        english_abbreviations=("2 kgs", "2ki"),
        telugu_aliases=("2 రాజులు",),
        long_church_names=("రెండవ రాజుల గ్రంథము",),
        spoken_variants=("రెండవ రాజులు",),
    ),
    BookEntry("1 Chronicles",
        english_aliases=("1 chronicles", "first chronicles"),
        english_abbreviations=("1 chron", "1 chr", "1ch"),
        telugu_aliases=("1 దినవృత్తాంతములు", "1 దినవృత్తాంతాలు"),
        long_church_names=("మొదటి దినవృత్తాంతముల గ్రంథము",),
        spoken_variants=("మొదటి దినవృత్తాంతములు", "మొదటి దినవృత్తాంతాలు"),
    ),
    BookEntry("2 Chronicles",
        english_aliases=("2 chronicles", "second chronicles"),
        english_abbreviations=("2 chron", "2 chr", "2ch"),
        telugu_aliases=("2 దినవృత్తాంతములు", "2 దినవృత్తాంతాలు"),
        long_church_names=("రెండవ దినవృత్తాంతముల గ్రంథము",),
        spoken_variants=("రెండవ దినవృత్తాంతములు", "రెండవ దినవృత్తాంతాలు"),
    ),
    BookEntry("Ezra",
        english_aliases=("ezra",),
        english_abbreviations=("ezr",),
        telugu_aliases=("ఎజ్రా",),
        long_church_names=("ఎజ్రా గ్రంథము", "ఎజ్రా గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Nehemiah",
        english_aliases=("nehemiah",),
        english_abbreviations=("neh", "ne"),
        telugu_aliases=("నెహెమ్యా",),
        long_church_names=("నెహెమ్యా గ్రంథము", "నెహెమ్యా గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Esther",
        english_aliases=("esther",),
        english_abbreviations=("esth", "est", "es"),
        telugu_aliases=("ఎస్తేరు",),
        long_church_names=("ఎస్తేరు గ్రంథము", "ఎస్తేరు గ్రంథం"),
        spoken_variants=(),
    ),

    # ---- Wisdom books ----
    BookEntry("Job",
        english_aliases=("job",),
        english_abbreviations=("jb",),
        telugu_aliases=("యోబు",),
        long_church_names=("యోబు గ్రంథము", "యోబు గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Psalms",
        english_aliases=("psalms", "psalm", "psalter"),
        english_abbreviations=("ps",),
        telugu_aliases=("కీర్తనలు", "కీర్తన"),
        long_church_names=("కీర్తనల గ్రంథము", "కీర్తనల గ్రంథం"),
        spoken_variants=("కీర్త", "క్రం"),
    ),
    BookEntry("Proverbs",
        english_aliases=("proverbs", "proverb"),
        english_abbreviations=("prov", "pro", "pr"),
        telugu_aliases=("సామెతలు", "సామెత"),
        long_church_names=("సామెతల గ్రంథము", "సామెతల గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Ecclesiastes",
        english_aliases=("ecclesiastes",),
        english_abbreviations=("eccl", "ecc", "ec"),
        telugu_aliases=("ప్రసంగి",),
        long_church_names=("ప్రసంగి గ్రంథము", "ప్రసంగి గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Song of Solomon",
        english_aliases=("song of solomon", "song of songs",),
        english_abbreviations=("song", "songs", "sos", "so"),
        telugu_aliases=("పరమగీతము", "పరమగీతం"),
        long_church_names=("పరమ గీతము",),
        spoken_variants=("పరమగీతము",),
    ),

    # ---- Major prophets ----
    BookEntry("Isaiah",
        english_aliases=("isaiah",),
        english_abbreviations=("isa",),
        telugu_aliases=("యెషయా",),
        long_church_names=("యెషయా గ్రంథము", "యెషయా గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Jeremiah",
        english_aliases=("jeremiah",),
        english_abbreviations=("jer", "je"),
        telugu_aliases=("యిర్మియా",),
        long_church_names=("యిర్మియా గ్రంథము", "యిర్మియా గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Lamentations",
        english_aliases=("lamentations",),
        english_abbreviations=("lam", "la"),
        telugu_aliases=("విలాపవాక్యములు", "విలాపవాక్యాలు"),
        long_church_names=("యిర్మియా విలాపవాక్యములు",),
        spoken_variants=(),
    ),
    BookEntry("Ezekiel",
        english_aliases=("ezekiel",),
        english_abbreviations=("ezek", "eze", "ez"),
        telugu_aliases=("యెహెజ్కేలు", "యెహెజ్కేల్"),
        long_church_names=("యెహెజ్కేలు గ్రంథము", "యెహెజ్కేలు గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Daniel",
        english_aliases=("daniel",),
        english_abbreviations=("dan", "dn"),
        telugu_aliases=("దానియేలు",),
        long_church_names=("దానియేలు గ్రంథము", "దానియేలు గ్రంథం"),
        spoken_variants=("దాని",),
    ),

    # ---- Minor prophets ----
    BookEntry("Hosea",
        english_aliases=("hosea",),
        english_abbreviations=("hos",),
        telugu_aliases=("హోషేయా",),
        long_church_names=("హోషేయా గ్రంథము", "హోషేయా గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Joel",
        english_aliases=("joel",),
        english_abbreviations=("joe", "jl"),
        telugu_aliases=("యోవేలు",),
        long_church_names=("యోవేలు గ్రంథము", "యోవేలు గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Amos",
        english_aliases=("amos",),
        english_abbreviations=("amo", "am"),
        telugu_aliases=("ఆమోసు",),
        long_church_names=("ఆమోసుకు వ్రాసిన గ్రంథము",),
        spoken_variants=("ఆమోసు గ్రంథము", "ఆమోసుకు"),
    ),
    BookEntry("Obadiah",
        english_aliases=("obadiah",),
        english_abbreviations=("obad", "ob"),
        telugu_aliases=("ఓబద్యా",),
        long_church_names=("ఓబద్యా గ్రంథము", "ఓబద్యా గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Jonah",
        english_aliases=("jonah",),
        english_abbreviations=("jon",),
        telugu_aliases=("యోనా",),
        long_church_names=("యోనా గ్రంథము", "యోనా గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Micah",
        english_aliases=("micah",),
        english_abbreviations=("mic",),
        telugu_aliases=("మీకా",),
        long_church_names=("మీకా గ్రంథము", "మీకా గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Nahum",
        english_aliases=("nahum",),
        english_abbreviations=("nah", "na"),
        telugu_aliases=("నహూము",),
        long_church_names=("నహూము గ్రంథము", "నహూము గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Habakkuk",
        english_aliases=("habakkuk",),
        english_abbreviations=("hab",),
        telugu_aliases=("హబక్కూకు",),
        long_church_names=("హబక్కూకు గ్రంథము", "హబక్కూకు గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Zephaniah",
        english_aliases=("zephaniah",),
        english_abbreviations=("zeph", "zep", "zp"),
        telugu_aliases=("జెఫన్యా",),
        long_church_names=("జెఫన్యా గ్రంథము", "జెఫన్యా గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Haggai",
        english_aliases=("haggai",),
        english_abbreviations=("hag",),
        telugu_aliases=("హగ్గయి",),
        long_church_names=("హగ్గయి గ్రంథము", "హగ్గయి గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Zechariah",
        english_aliases=("zechariah",),
        english_abbreviations=("zech", "zec", "zc"),
        telugu_aliases=("జెకర్యా",),
        long_church_names=("జెకర్యా గ్రంథము", "జెకర్యా గ్రంథం"),
        spoken_variants=(),
    ),
    BookEntry("Malachi",
        english_aliases=("malachi",),
        english_abbreviations=("mal", "ml"),
        telugu_aliases=("మలాకీ",),
        long_church_names=("మలాకీ గ్రంథము", "మలాకీ గ్రంథం"),
        spoken_variants=(),
    ),

    # ---- Gospels ----
    BookEntry("Matthew",
        english_aliases=("matthew", "gospel of matthew"),
        english_abbreviations=("matt", "mat", "mt"),
        telugu_aliases=("మత్తయి",),
        long_church_names=("మత్తయి సువార్త",),
        spoken_variants=("మత్త",),
    ),
    BookEntry("Mark",
        english_aliases=("mark", "gospel of mark"),
        english_abbreviations=("mrk", "mk"),
        telugu_aliases=("మార్కు",),
        long_church_names=("మార్కు సువార్త",),
        spoken_variants=(),
    ),
    BookEntry("Luke",
        english_aliases=("luke", "gospel of luke"),
        english_abbreviations=("luk", "lk"),
        telugu_aliases=("లూకా",),
        long_church_names=("లూకా సువార్త",),
        spoken_variants=(),
    ),
    BookEntry("John",
        english_aliases=("john", "gospel of john"),
        english_abbreviations=("joh", "jn"),
        telugu_aliases=("యోహాను", "యోహను"),
        long_church_names=("యోహాను సువార్త",),
        spoken_variants=("యోహ", "యోహానూ", "యోహాన"),
    ),

    # ---- History (NT) ----
    BookEntry("Acts",
        english_aliases=("acts", "acts of the apostles"),
        english_abbreviations=("act", "ac"),
        telugu_aliases=("అపొస్తలుల కార్యములు", "అపొస్తలుల కార్యాలు"),
        long_church_names=("అపొస్తలుల కార్యములు",),
        spoken_variants=("అపొస్తలుల",),
    ),

    # ---- Pauline epistles ----
    BookEntry("Romans",
        english_aliases=("romans", "epistle to the romans"),
        english_abbreviations=("rom", "ro", "rm"),
        telugu_aliases=("రోమీయులకు",),
        long_church_names=("రోమీయులకు వ్రాసిన పత్రిక",),
        spoken_variants=("రోమీ", "రోమీయులుకు", "రోమియులకు"),
    ),
    BookEntry("1 Corinthians",
        english_aliases=("1 corinthians", "first corinthians"),
        english_abbreviations=("1 cor", "1co"),
        telugu_aliases=("1 కొరింథీయులకు",),
        long_church_names=("మొదటి కొరింథీయులకు వ్రాసిన పత్రిక",),
        spoken_variants=("మొదటి కొరింథీయులకు", "1 కొరింథీ"),
    ),
    BookEntry("2 Corinthians",
        english_aliases=("2 corinthians", "second corinthians"),
        english_abbreviations=("2 cor", "2co"),
        telugu_aliases=("2 కొరింథీయులకు",),
        long_church_names=("రెండవ కొరింథీయులకు వ్రాసిన పత్రిక",),
        spoken_variants=("రెండవ కొరింథీయులకు", "2 కొరింథీ"),
    ),
    BookEntry("Galatians",
        english_aliases=("galatians", "epistle to the galatians"),
        english_abbreviations=("gal", "ga"),
        telugu_aliases=("గలతీయులకు",),
        long_church_names=("గలతీయులకు వ్రాసిన పత్రిక",),
        spoken_variants=("గలతీ",),
    ),
    BookEntry("Ephesians",
        english_aliases=("ephesians", "epistle to the ephesians"),
        english_abbreviations=("eph", "ep"),
        telugu_aliases=("ఎఫెసీయులకు",),
        long_church_names=("ఎఫెసీయులకు వ్రాసిన పత్రిక",),
        spoken_variants=("ఎఫెసీ",),
    ),
    BookEntry("Philippians",
        english_aliases=("philippians", "epistle to the philippians"),
        english_abbreviations=("phil", "php"),
        telugu_aliases=("ఫిలిప్పీయులకు",),
        long_church_names=("ఫిలిప్పీయులకు వ్రాసిన పత్రిక",),
        spoken_variants=("ఫిలిప్పీ", "ఫిలిప్పి"),
    ),
    BookEntry("Colossians",
        english_aliases=("colossians", "epistle to the colossians"),
        english_abbreviations=("col", "cl"),
        telugu_aliases=("కొలొస్సయులకు",),
        long_church_names=("కొలొస్సయులకు వ్రాసిన పత్రిక",),
        spoken_variants=("కొలొస్స",),
    ),
    BookEntry("1 Thessalonians",
        english_aliases=("1 thessalonians", "first thessalonians"),
        english_abbreviations=("1 thess", "1th"),
        telugu_aliases=("1 థెస్సలొనీకయులకు",),
        long_church_names=("మొదటి థెస్సలొనీకయులకు వ్రాసిన పత్రిక",),
        spoken_variants=("మొదటి థెస్సలొనీకయులకు", "1 థెస్సలొనీక"),
    ),
    BookEntry("2 Thessalonians",
        english_aliases=("2 thessalonians", "second thessalonians"),
        english_abbreviations=("2 thess", "2th"),
        telugu_aliases=("2 థెస్సలొనీకయులకు",),
        long_church_names=("రెండవ థెస్సలొనీకయులకు వ్రాసిన పత్రిక",),
        spoken_variants=("రెండవ థెస్సలొనీకయులకు", "2 థెస్సలొనీక"),
    ),
    BookEntry("1 Timothy",
        english_aliases=("1 timothy", "first timothy"),
        english_abbreviations=("1 tim", "1ti"),
        telugu_aliases=("1 తిమోతికి",),
        long_church_names=("మొదటి తిమోతికి వ్రాసిన పత్రిక",),
        spoken_variants=("మొదటి తిమోతికి", "1 తిమోతి"),
    ),
    BookEntry("2 Timothy",
        english_aliases=("2 timothy", "second timothy"),
        english_abbreviations=("2 tim", "2ti"),
        telugu_aliases=("2 తిమోతికి",),
        long_church_names=("రెండవ తిమోతికి వ్రాసిన పత్రిక",),
        spoken_variants=("రెండవ తిమోతికి", "2 తిమోతి"),
    ),
    BookEntry("Titus",
        english_aliases=("titus", "epistle to titus"),
        english_abbreviations=("tit", "ti"),
        telugu_aliases=("తీతుకు", "తీతు"),
        long_church_names=("తీతుకు వ్రాసిన పత్రిక",),
        spoken_variants=("తీతు పత్రిక",),
    ),
    BookEntry("Philemon",
        english_aliases=("philemon", "epistle to philemon"),
        english_abbreviations=("philem", "phm", "pm"),
        telugu_aliases=("ఫిలేమోనుకు", "ఫిలేమోను"),
        long_church_names=("ఫిలేమోనుకు వ్రాసిన పత్రిక",),
        spoken_variants=("ఫిలేమోను పత్రిక",),
    ),

    # ---- General epistles ----
    BookEntry("Hebrews",
        english_aliases=("hebrews", "epistle to the hebrews"),
        english_abbreviations=("heb", "he"),
        telugu_aliases=("హెబ్రీయులకు",),
        long_church_names=("హెబ్రీయులకు వ్రాసిన పత్రిక",),
        spoken_variants=("హెబ్రీ",),
    ),
    BookEntry("James",
        english_aliases=("james", "epistle of james"),
        english_abbreviations=("jas", "jm"),
        telugu_aliases=("యాకోబు",),
        long_church_names=("యాకోబు పత్రిక",),
        spoken_variants=(),
    ),
    BookEntry("1 Peter",
        english_aliases=("1 peter", "first peter"),
        english_abbreviations=("1 pet", "1pe"),
        telugu_aliases=("1 పేతురు",),
        long_church_names=("మొదటి పేతురు పత్రిక",),
        spoken_variants=("మొదటి పేతురు",),
    ),
    BookEntry("2 Peter",
        english_aliases=("2 peter", "second peter"),
        english_abbreviations=("2 pet", "2pe"),
        telugu_aliases=("2 పేతురు",),
        long_church_names=("రెండవ పేతురు పత్రిక",),
        spoken_variants=("రెండవ పేతురు",),
    ),
    BookEntry("1 John",
        english_aliases=("1 john", "first john"),
        english_abbreviations=("1 jn", "1jo"),
        telugu_aliases=("1 యోహాను",),
        long_church_names=("మొదటి యోహాను పత్రిక",),
        spoken_variants=("మొదటి యోహాను",),
    ),
    BookEntry("2 John",
        english_aliases=("2 john", "second john"),
        english_abbreviations=("2 jn", "2jo"),
        telugu_aliases=("2 యోహాను",),
        long_church_names=("రెండవ యోహాను పత్రిక",),
        spoken_variants=("రెండవ యోహాను",),
    ),
    BookEntry("3 John",
        english_aliases=("3 john", "third john"),
        english_abbreviations=("3 jn", "3jo"),
        telugu_aliases=("3 యోహాను",),
        long_church_names=("మూడవ యోహాను పత్రిక",),
        spoken_variants=("మూడవ యోహాను",),
    ),
    BookEntry("Jude",
        english_aliases=("jude", "epistle of jude"),
        english_abbreviations=("jud", "jd"),
        telugu_aliases=("యూదా",),
        long_church_names=("యూదా పత్రిక",),
        spoken_variants=(),
    ),

    # ---- Prophecy (NT) ----
    BookEntry("Revelation",
        english_aliases=("revelation", "book of revelation"),
        english_abbreviations=("rev", "re"),
        telugu_aliases=("ప్రకటన",),
        long_church_names=("ప్రకటన గ్రంథము", "ప్రకటన గ్రంధము"),
        spoken_variants=("ప్రక", "యోహాను ప్రకటన"),
    ),
)


def whisper_vocabulary_terms() -> list[str]:
    terms: list[str] = []
    seen: set[str] = set()

    for entry in BOOKS:
        for term in (entry.canonical, *entry.aliases):
            normalized = term.strip()
            if not normalized:
                continue

            key = normalized.casefold()
            if key in seen:
                continue

            seen.add(key)
            terms.append(normalized)

    extra_words = (
        "chapter", "verse", "verses", "book", "scripture",
        "అధ్యాయం", "వచనం", "వచనము", "గ్రంథము", "సువార్త"
    )
    for term in extra_words:
        key = term.casefold()
        if key not in seen:
            seen.add(key)
            terms.append(term)

    return terms


def whisper_initial_prompt() -> str:
    terms = whisper_vocabulary_terms()
    return (
        "This audio contains Bible references spoken in Telugu, English, and mixed language. "
        "Use this vocabulary: " + ", ".join(terms) + "."
    )
